name: csg4-forumestudantil-python

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install AWS CLI 2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ASIATPW6DPD2TJON4VGV
          aws-secret-access-key: jufdknGlsx2ofOe7tSsTNDBPPZRbOOYWkuCT/3lG
          aws-session-token: FwoGZXIvYXdzECkaDAzbNTBWt8cbtUS//SLHAVC6mUJ+OcE2p0Wa/bti0KDA64wFj0U1K7yyJ/7gOPaTG76S4IcN4BoiySohmIRE/rXQ+eKgmVreTVwDe0OdXCncfolAqYtYspt7FbZsKrdKnOVOHejuHGO0g5AsDWeAoGNB4xVAxbcFYJrvrbnHgmm8OiI+nO8b4S9Qj1EmrLT2eux6lJgpo4aIJWxx9wB/AC3WQuZuCl+9mwzZDGhUKWBNwm7XLzeYaznofdhpxLRGEy9pouN4+Adn8smXh4YGMtFTZVEJFzMooN2+qwYyLVFdACeEg2Lg3GUdsk9IZB5jNKM921KyeVCkWQS3+Mur+z95zW7ABlXvQQqseA==
          aws-region: us-east-1

      - uses: actions/checkout@v2
      - name: Terraform infra provisioning
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.3.7"
      
      - name: Terraform init
        run: terraform init
        working-directory: ./infra

      - name: Terraform apply
        run: terraform apply --auto-approve
        working-directory: ./infra

      - name: AWS Deploy push
        working-directory: .
        run: |
          aws deploy push \
          --application-name csg4-forumestudantil-application \
          --ignore-hidden-files \
          --s3-location s3://csg4-forumestudantil-codedeploy-deployments/csg4-forumestudantil-deployment-${{ github.sha }}.zip \
          --source .

      - name: AWS Create Deployment
        working-directory: .
        run: |
          aws deploy create-deployment \
          --application-name csg4-forumestudantil-application \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name csg4-forumestudantil-deployment-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=csg4-forumestudantil-codedeploy-deployments,key=csg4-forumestudantil-deployment-${{ github.sha }}.zip,bundleType=zip \